### ISSUE TITLE
Dumb question: How to connect to proxy from the old browser?

### ISSUE THREAD

**Issue by mjb006** [midwesterntechnology/vintage-proxy#1]
Hi.
I have two computers on my network. One is a modern computer running the vintage-proxy server. The other is an old desktop. I tried setting the desktop to connect to the proxy server by configuring the browser to use the IP address of the computer running the server on port 3000, but it won't connect. I'm new to this and not sure what I'm doing wrong.

**Comment by ispb88** [comment]
Based on what you've said, it should work. Try visiting the IP address at port 3000 in your browser and see what comes up.

**Comment by mjb006** [comment]
Oops. Typo in IP address. Thanks
